### ISSUE TITLE
Cannot evaluate expression Cannot evaluate function  WIN-TEKVN09P1GI:ms.hyperv[full].nodata(30m)  item does not have enough data after server start or item creation 

### ISSUE THREAD

**Issue by 549353365** [asand3r/zbx-hyperv#3]
Cannot evaluate expression Cannot evaluate function  WIN-TEKVN09P1GI:ms.hyperv[full].nodata(30m)  item does not have enough data after server start or item creation

**Comment by asand3r** [comment]
Not a script issue
