### ISSUE TITLE
ZBX_NOTSUPPORTED: Timeout while executing a shell script.

### ISSUE THREAD

**Issue by DemonKZ** [asand3r/zbx-hyperv#6]
zabbix_get -s severXXXX -p 10050 -k "ms.hyperv[full]"

![image](https://user-images.githubusercontent.com/61456615/101328404-26ae2c80-389a-11eb-893a-da3277f441f8.png)

Добрый день, отличный шаблон, но на некоторых хостах получаем ошибку, таймауты выставлены на максималку, 
Zabbix 5.0.2
Windows 2012 r2

**Comment by asand3r** [comment]
Добрый.
Да, такое может быть, это PowerShell. Могу только посоветовать использовать zabbix_sender.

**Comment by DemonKZ** [comment]
есть шаблоны?
